# -*- coding: utf-8 -*-
"""🧪 CanaryLab — Progressive Delivery Canary Analysis Simulator.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1sEyvWd3UiDWmKNrdVAn4E3hqiXSSDK
"""

# 🧪 CanaryLab — Progressive Delivery Canary Analysis Simulator
# Single-cell Colab code
# Deps: numpy, pandas, matplotlib (preinstalled in Colab)
#
# Generates:
#   - canary_samples.csv
#   - canary_compare.png
#   - Console verdict (PASS/FAIL + reasons)
#
# Author: Siddharth Raut — DevOps & Cloud Engineer

import time
from dataclasses import dataclass, field
from typing import Dict, Any
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# Reproducibility
# -----------------------------
np.random.seed(int(time.time()) % (2**32 - 1))

# -----------------------------
# Traffic & Metric Simulation
# -----------------------------
@dataclass
class TrafficSplit:
    baseline: float = 0.9
    canary: float = 0.1

    def normalized(self):
        s = self.baseline + self.canary
        if s <= 0:
            return TrafficSplit(0.9, 0.1)
        return TrafficSplit(self.baseline / s, self.canary / s)

@dataclass
class MetricSim:
    base_latency_ms: float = 120.0
    base_error_rate: float = 0.010
    canary_delta_lat_ms: float = 18.0
    canary_delta_error: float = 0.006
    latency_sigma_ms: float = 25.0

    def generate(self, n: int, split: TrafficSplit) -> pd.DataFrame:
        """
        Generate n requests, split between baseline and canary.
        Returns a DataFrame with columns: is_canary, latency_ms, error
        """
        split = split.normalized()
        # Route each request to canary with probability split.canary
        is_canary = np.random.rand(n) < split.canary

        # Base latency distribution
        latency = np.random.normal(self.base_latency_ms, self.latency_sigma_ms, size=n)

        # Base errors (Bernoulli)
        errors = (np.random.rand(n) < self.base_error_rate)

        # Apply deltas for canary traffic
        latency[is_canary] += self.canary_delta_lat_ms
        # Re-draw error for the canary subset using elevated rate
        canary_idx = np.where(is_canary)[0]
        if len(canary_idx) > 0:
            elevated = self.base_error_rate + self.canary_delta_error
            errors[canary_idx] = (np.random.rand(len(canary_idx)) < elevated)

        df = pd.DataFrame({
            "is_canary": is_canary.astype(bool),
            "latency_ms": latency.astype(float),
            "error": errors.astype(int)
        })
        return df

# -----------------------------
# Simple Welch t-test (no SciPy)
# -----------------------------
def welch_t_test(a: np.ndarray, b: np.ndarray):
    """
    Return (t, p_approx) using a normal-approximation for p-value.
    For demo purposes only (not a production-grade stats lib).
    """
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    ma, mb = np.mean(a), np.mean(b)
    va, vb = np.var(a, ddof=1), np.var(b, ddof=1)
    na, nb = len(a), len(b)
    denom = np.sqrt(va / max(na,1) + vb / max(nb,1) + 1e-12)
    t = (ma - mb) / denom if denom > 0 else 0.0

    # two-tailed p using Normal(0,1) CDF approximation
    from math import erf, sqrt
    p = 2.0 * (1.0 - 0.5 * (1.0 + erf(abs(t) / sqrt(2.0))))
    return float(t), float(p)

# -----------------------------
# Analyzer
# -----------------------------
@dataclass
class CanaryAnalyzer:
    split: TrafficSplit = field(default_factory=lambda: TrafficSplit(0.9, 0.1))
    sim: MetricSim = field(default_factory=MetricSim)
    history: pd.DataFrame = field(default_factory=pd.DataFrame)

    def run(self, steps: int = 6, batch: int = 1200) -> pd.DataFrame:
        """
        Run multiple sampling windows (steps), each with 'batch' requests.
        """
        frames = []
        for i in range(1, steps + 1):
            df = self.sim.generate(batch, self.split)
            df["step"] = i
            frames.append(df)
        self.history = pd.concat(frames, ignore_index=True)
        return self.history

    def analyze(self,
                error_ratio_limit: float = 1.5,
                max_latency_delta_ms: float = 20.0) -> Dict[str, Any]:
        """
        Decide PASS/FAIL based on:
          - Canary error rate not exceeding baseline by error_ratio_limit (e.g., 1.5x)
          - Canary mean latency not exceeding baseline by max_latency_delta_ms
        """
        if self.history.empty:
            return {"verdict": "UNKNOWN", "reasons": ["No data"]}

        df = self.history
        can = df[df["is_canary"] == True]
        base = df[df["is_canary"] == False]

        # Latencies
        can_lat = can["latency_ms"].values
        base_lat = base["latency_ms"].values
        t_lat, p_lat = welch_t_test(can_lat, base_lat)

        # Errors
        can_err = float(can["error"].mean())
        base_err = float(base["error"].mean())

        # Heuristics
        verdict = "PASS"
        reasons = []

        # Error rate comparison
        if base_err > 0 and (can_err > base_err * error_ratio_limit):
            verdict = "FAIL"
            reasons.append(f"Canary error rate too high ({can_err:.3f} vs {base_err:.3f} baseline)")

        # Latency delta comparison
        lat_delta = float(np.mean(can_lat) - np.mean(base_lat))
        if lat_delta > max_latency_delta_ms:
            verdict = "FAIL"
            reasons.append(f"Canary latency regression (+{lat_delta:.1f} ms > {max_latency_delta_ms} ms limit)")

        # Build summary
        summary = {
            "baseline_latency_ms": float(np.mean(base_lat)),
            "canary_latency_ms": float(np.mean(can_lat)),
            "baseline_error_rate": base_err,
            "canary_error_rate": can_err,
            "t_latency": t_lat,
            "p_latency_approx": p_lat,
            "latency_delta_ms": lat_delta,
            "error_ratio_limit": error_ratio_limit,
            "max_latency_delta_ms": max_latency_delta_ms,
            "verdict": verdict,
            "reasons": reasons
        }
        # Pretty print
        print("=== Canary Analysis ===")
        for k in ["baseline_latency_ms","canary_latency_ms",
                  "baseline_error_rate","canary_error_rate",
                  "t_latency","p_latency_approx","latency_delta_ms",
                  "error_ratio_limit","max_latency_delta_ms","verdict"]:
            print(f"{k}: {summary[k]}")
        if reasons:
            print("reasons:", reasons)
        return summary

    def plot(self, outfile: str = "canary_compare.png"):
        """
        Create a 2-panel figure:
          (1) Latency histograms (baseline vs canary)
          (2) Error rate by step (baseline vs canary)
        """
        df = self.history
        if df.empty:
            print("No history to plot.")
            return

        plt.figure(figsize=(10, 7))

        # Panel 1: Latency histogram
        plt.subplot(2, 1, 1)
        base_lat = df[df.is_canary == False]["latency_ms"]
        can_lat = df[df.is_canary == True]["latency_ms"]
        plt.hist(base_lat, bins=30, alpha=0.6, label="Baseline")
        plt.hist(can_lat, bins=30, alpha=0.6, label="Canary")
        plt.title("Latency Distribution")
        plt.xlabel("Latency (ms)")
        plt.ylabel("Count")
        plt.legend()

        # Panel 2: Error rate by step
        plt.subplot(2, 1, 2)
        err = df.groupby(["step", "is_canary"])["error"].mean().unstack(fill_value=0)
        err.rename(columns={False: "Baseline", True: "Canary"}, inplace=True)
        err.plot(ax=plt.gca())
        plt.title("Error Rate by Step")
        plt.xlabel("Step")
        plt.ylabel("Error Rate")
        plt.tight_layout()
        plt.savefig(outfile, dpi=220)
        print(f"Saved → {outfile}")

# -----------------------------
# Quick Demo (adjust as needed)
# -----------------------------
if __name__ == "__main__":
    analyzer = CanaryAnalyzer(
        split=TrafficSplit(baseline=0.9, canary=0.1),
        sim=MetricSim(
            base_latency_ms=120.0,
            base_error_rate=0.010,
            canary_delta_lat_ms=18.0,
            canary_delta_error=0.006,
            latency_sigma_ms=25.0
        )
    )

    # Run simulation (6 windows, 1200 requests each)
    analyzer.run(steps=6, batch=1200)

    # Analyze & print verdict
    result = analyzer.analyze(error_ratio_limit=1.5, max_latency_delta_ms=20.0)

    # Save artifacts
    analyzer.plot("canary_compare.png")
    analyzer.history.to_csv("canary_samples.csv", index=False)
    print("Saved → canary_samples.csv")